version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: product
      MYSQL_USER: root
      MYSQL_PASSWORD: ""  # Optional; can be omitted
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3

  app:
    container_name: SpringBoot-Product-Thymeleaf
    build: .
    ports:
      - "5555:5555"
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.jpa.properties.javax.persistence.validation.mode=none
      - spring.datasource.url=jdbc:mysql://mysql:3306/product
      - spring.datasource.username=root
      - spring.datasource.password=  # Empty password
      - spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=false
      - spring.datasource.hikari.auto-commit=false
    restart: always
    depends_on:
      - mysql

volumes:
  mysql_data:
